data:
  evfile : path_to_data_folder/events.txt
  scfile : path_to_data_folder/spacecraft.fits

binning:
  roiwidth   : 8.0
  binsz      : 0.1 # spatial bin size in deg
  binsperdec : 10   # nb energy bins per decade
#  projtype   : WCS

selection :
  emin : 100
  emax : 1000000
  zmax    : 90
  evclass : 128
  evtype  : 3
  filter : 'DATA_QUAL>0 && LAT_CONFIG==1'  

gtlike:
  edisp : True
  irfs : 'P8R3_SOURCE_V3'
  edisp_disable : ['isodiff','galdiff']

model:
  src_radius : 6.0
  galdiff  : '$FERMI_DIR/refdata/fermi/galdiffuse/gll_iem_v07.fits'
  isodiff  : '$FERMI_DIR/refdata/fermi/galdiffuse/iso_P8R3_SOURCE_V3_v1.txt' 

optimizer:
  min_fit_quality: 3
  retries : 5
 
